// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkEEQqDS_ZOAkQNyi36fpwtUbyZJyGNYA',
    appId: '1:73104170290:web:96a1aa7161cfdf260d0b2b',
    messagingSenderId: '73104170290',
    projectId: 'authentication-flutter-6e058',
    authDomain: 'authentication-flutter-6e058.firebaseapp.com',
    storageBucket: 'authentication-flutter-6e058.appspot.com',
    measurementId: 'G-T59Z4VPY1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAv5VL43jKl_XrKrmNGiTYrdcItVUjHe4',
    appId: '1:73104170290:android:d08fe90396c10ca60d0b2b',
    messagingSenderId: '73104170290',
    projectId: 'authentication-flutter-6e058',
    storageBucket: 'authentication-flutter-6e058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLsdM5cpQDv-t0CnwtN8SnV6OxMk2Q3E',
    appId: '1:73104170290:ios:ce43f6e53ce3f8d50d0b2b',
    messagingSenderId: '73104170290',
    projectId: 'authentication-flutter-6e058',
    storageBucket: 'authentication-flutter-6e058.appspot.com',
    iosBundleId: 'com.example.newapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLsdM5cpQDv-t0CnwtN8SnV6OxMk2Q3E',
    appId: '1:73104170290:ios:ce43f6e53ce3f8d50d0b2b',
    messagingSenderId: '73104170290',
    projectId: 'authentication-flutter-6e058',
    storageBucket: 'authentication-flutter-6e058.appspot.com',
    iosBundleId: 'com.example.newapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkEEQqDS_ZOAkQNyi36fpwtUbyZJyGNYA',
    appId: '1:73104170290:web:5153ad5d96b27a300d0b2b',
    messagingSenderId: '73104170290',
    projectId: 'authentication-flutter-6e058',
    authDomain: 'authentication-flutter-6e058.firebaseapp.com',
    storageBucket: 'authentication-flutter-6e058.appspot.com',
    measurementId: 'G-464RK1N3FZ',
  );
}
